/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_copy_LibCopy */

#ifndef _Included_lib_copy_LibCopy
#define _Included_lib_copy_LibCopy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_copy_LibCopy
 * Method:    copyF
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lib_copy_LibCopy_copyF
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
